### ISSUE TITLE
Support Docker Containers

### ISSUE THREAD

**Issue by mosoriob** [mintproject/dame_cli#15]
**Is your feature request related to a problem? Please describe.**
Support run the containers using Docker.

**Describe the solution you'd like**
The user can choose Docker to run the containers

**Comment by dgarijo** [comment]
Note that DAME already 'supports' Docker containers, but they are executed through Singularity. This feature would be to support Docker independently.

**Comment by dgarijo** [comment]
After discussion with @sirspock, this is now required to run images in MacOS. 
The workflow will be: We will try to execute first the singularity command. If it fails, we will execute/allow executing a Docker command. For example, for HAND: docker run -ti  -v $PWD:/mint  -w /mint  mintproject/hand:v2.1.0 ./run  -i1 Travis-DEM-10m-HUC120902050408buf.tif  -o1 distance-down.tif -o3 shape.shp -o4 geojson.json -o2 distance-down-raster.tif  -p1 500

**Comment by mosoriob** [comment]
Done. This is a Beta.

On Windows and macOS, Dame uses Docker.
On Linux, Dame use singularity. If you don't have installed singularity then DAME is going to use Docker.

**Comment by mosoriob** [comment]
Needs testing using different setups

**Comment by dgarijo** [comment]
I would like to test this in Windows too. Are there special instructions, or will the system runn automatically? I will assign this to me for testing.

**Comment by dgarijo** [comment]
I tested in Windows. Command: `pip install dame-cli -e .`

Run: `dame run cycles-0.10.2-alpha-collection-oromia-single-point`

Result:
```bash
Information about the model configuration
Inputs
- cycles_weather_soil: https://data.mint.isi.edu/files/cycles-input-data/oromia/weather-soil/Arsi_Amigna_7.884865046N_40.19527054E.zip
- cycles_crops: https://raw.githubusercontent.com/pegasus-isi/pegasus-cycles/master/data/crops.crop
Parameters
- start_planting_day: 100
- end_year: 2017
- fertilizer_rate: 0
- crop_name: Maize
- end_planting_day: 149
- use_forcing: FALSE
- weed_fraction: 0.05
- start_year: 2000
- Name: mintproject/cycles:0.10.2-alpha - https://hub.docker.com/r/mintproject/cycles
Component Location
- Link: https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/cycles-0.10.2-alpha-collection/cycles-0.10.2-alpha-collection.zip
The information needed to run the model is complete, and I can execute the model as follows:
Traceback (most recent call last):
  File "C:\Users\dgarijo\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dgarijo\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dgarijo\Documents\GitHub\dame_cli\Scripts\dame.exe\__main__.py", line 9, in <module>
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\dame\__main__.py", line 81, in run
    run_method_setup(resource, interactive)
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\dame\cli_methods.py", line 147, in run_method_setup
    if not find_singularity():
  File "c:\users\dgarijo\documents\github\dame_cli\lib\site-packages\dame\utils.py", line 22, in find_singularity
    if pathlib.Path(SINGULARITY_CWD_LINE).exists():
UnboundLocalError: local variable 'SINGULARITY_CWD_LINE' referenced before assignment
```

**Comment by mosoriob** [comment]
Can you retry it?

**Comment by dgarijo** [comment]
I have tested it successfully in Windows

**Comment by dgarijo** [comment]
The only issue I saw is that the log doesn't show whether it's downloading the image or not, so it's difficult to know what is going on.

**Comment by mosoriob** [comment]
A progress bar has been included
