### ISSUE TITLE
Error when executing Setup

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#25]
**Describe the bug**
`dame run 7d9ac3ba-c575-467e-9183-e85711b0f8d8`
Error:
```
Traceback (most recent call last):
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/cli_methods.py", line 136, in execute_setups
    status, file_dir = execute_setup(setup_files)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 108, in execute_setup
    raise e
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 106, in execute_setup
    setup_cmd_line, cwd_path = build_command_line(setup_dict, execution_dir_path)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 83, in build_command_line
    l = build_input(inputs, src_path)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 31, in build_input
    position = _input["position"][0]
KeyError: 'position'
```
This setup corresponds to https://rdfexplorer.mint.isi.edu/page/okn/i/mint/7d9ac3ba-c575-467e-9183-e85711b0f8d8

This setup was created automatically with the portal. It is equivalent to others like https://rdfexplorer.mint.isi.edu/page/okn/i/mint/a044daca-eb62-4ef9-b806-508e0cee27fa

All input/outputs have `position` (I checked)

**Comment by dgarijo** [comment]
Curiously, 
`dame run 677c434e-99e2-4113-a5c4-4160f10bbb9a` which is a copy of the setup, has started the execution successfully.

**Comment by dgarijo** [comment]
This was a problem in the API, and it was successfully executed after fix
