### ISSUE TITLE
Incomplete configurations fail

### ISSUE THREAD

**Issue by dgarijo** [mintproject/dame_cli#26]
I installed dame-cli from scratch:
`pip install -I dame-cli`
and when doing
`dame run cycles-0.10.2-alpha-collection`
I got the following result:
```
The information of the setup is complete
Executing the setup
2020-04-16 20:16:34,008 root         ERROR    'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/cli_methods.py", line 136, in execute_setups
    status, file_dir = execute_setup(setup_files)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 108, in execute_setup
    raise e
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 106, in execute_setup
    setup_cmd_line, cwd_path = build_command_line(setup_dict, execution_dir_path)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 83, in build_command_line
    l = build_input(inputs, src_path)
  File "/data/users/runner/.venv/lib/python3.6/site-packages/dame/executor.py", line 29, in build_input
    url = _input["has_fixed_resource"][0]["value"][0]
TypeError: 'NoneType' object is not subscriptable
```
The configuration is NOT complete, it should ask for the input (hence the error makes sense). Is there a problem in the API?

**Comment by mosoriob** [comment]
Fixed: https://github.com/mintproject/dame_cli/releases/tag/3.4.0

```
dame run cycles-0.10.2-alpha-collection                                                         took 14s Py dame-prod
The information of the setup is incomplete
+--------------------+-----------------------------------------------------------------------------+
|      Property      |                                    Value                                    |
+====================+=============================================================================+
| has_dimensionality | [0]                                                                         |
+--------------------+-----------------------------------------------------------------------------+
| has_format         | ['crop']                                                                    |
+--------------------+-----------------------------------------------------------------------------+
| description        | ['The crop description file defines physiological and management parameters |
|                    | that control the growth and harvest of crops used in the simulation. Each   |
|                    | crop used in the simulation must have an entry in the crop description      |
|                    | file. Each crop entry begins with the keyword tag NAME.']                   |
+--------------------+-----------------------------------------------------------------------------+
| position           | [2]                                                                         |
+--------------------+-----------------------------------------------------------------------------+
| id                 | https://w3id.org/okn/i/mint/cycles-0.10.2-alpha-collection_crops            |
+--------------------+-----------------------------------------------------------------------------+
| label              | ['cycles_crops']                                                            |
+--------------------+-----------------------------------------------------------------------------+
Please, enter the url of the previous input:
```
