### ISSUE TITLE
Verify the execution

### ISSUE THREAD

**Issue by mosoriob** [mintproject/dame_cli#88]
I also tried it with `dame run 5630a04c-ef7c-436e-8ac4-9210da7c4eec` for one of the resources in this model: https://wifire.models.mint.isi.edu/models/explore/quic_fire/079abcb9-4277-4800-8a70-966947a83f1c/dee50e48-091f-471d-ae41-5dde3f467891/5630a04c-ef7c-436e-8ac4-9210da7c4eec

_Originally posted by @iperezx in https://github.com/mintproject/dame_cli/issues/87#issuecomment-822858159_

**Comment by iperezx** [comment]
It can now be executed with wifire mint instance but I get an runtime error. Here is the output:
`Desktop dame run 5630a04c-ef7c-436e-8ac4-9210da7c4eec

Information about the model configuration
Parameters
- Ignition location longitude: 38.939
- Wind speed: 0
- Fuel moisture: FALSE
- Energy to atmosphere: FALSE
- Wind direction: 180
- Fuel density: TRUE
- Ignition location latitude: -120.7366
Docker Image
- Name: hvarg/download-example - https://hub.docker.com/r/hvarg/download-example 
Component Location
- Link: https://github.com/hvarg/download-example/raw/master/mint_component.zip
Do you want to edit the parameters? [y/N]: N
Engine: DOCKER
Invocation command 
cd executions/5630a04c-ef7c-436e-8ac4-9210da7c4eec_eeac4b5c-a1f6-11eb-b291-acde48001122/mic/src
docker run -ti -v /Users/iperezx/Desktop/executions/5630a04c-ef7c-436e-8ac4-9210da7c4eec_eeac4b5c-a1f6-11eb-b291-acde48001122/mic/src:/tmp/mint -w /tmp/mint hvarg/download-example ./run   -p1 38.939 -p3 0 -p6 FALSE -p7 FALSE -p4 180 -p5 TRUE -p2 -120.7366
Do you want to proceed and submit it for execution? [Y/n]: Y
2021-04-20 09:39:14,259 root         ERROR    __init__() missing 1 required positional argument: 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=hvarg%2Fdownload-example

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dame/executor.py", line 168, in docker_pull
    result_itr = client.pull(image, stream=True, decode=True)
  File "/usr/local/lib/python3.9/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=hvarg%2Fdownload-example: Not Found ("manifest for hvarg/download-example:latest not found: manifest unknown: manifest unknown")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dame/cli_methods.py", line 188, in run_method_setup
    execute_setups(component_src_dir, execution_dir, setup_cmd_line, setup_name, image, interactive)
  File "/usr/local/lib/python3.9/site-packages/dame/cli_methods.py", line 216, in execute_setups
    raise e
  File "/usr/local/lib/python3.9/site-packages/dame/cli_methods.py", line 214, in execute_setups
    run_docker(setup_cmd_line, execution_dir, component_src_dir, setup_name, image, mint_volumes)
  File "/usr/local/lib/python3.9/site-packages/dame/executor.py", line 183, in run_docker
    docker_pull(client, image)
  File "/usr/local/lib/python3.9/site-packages/dame/executor.py", line 170, in docker_pull
    raise docker.errors.APIError
TypeError: __init__() missing 1 required positional argument: 'message'
[5630a04c-ef7c-436e-8ac4-9210da7c4eec] The execution has failed`

Maybe the model information in the catalog does not have the latest information for the docker image?

**Comment by mosoriob** [comment]
Yes, the correct image is  `hvarg/download-example:21.3` but configuration is pointing to `hvarg/download-example:latest`.

@hvarg is going to push the image.
